version: '2'
services:
  mysql:
        image: mysql:5.7
        container_name: mysql-server-5.7

# 	Set default auth mysql settings
# 	Set utf-8 charset 
        command: [
          '--default_authentication_plugin=mysql_native_password',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci'
        ]
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=admin_pass
          - MYSQL_DATABASE=social_network_db
          - MYSQL_USER=social_user
          - MYSQL_PASSWORD=social_pass
        ports:
          - "8082:3306"
  website:
    container_name: php-7.3
    build:
      context: ./
    volumes:
      - /home/kali/projects/social_network/app/:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql
